const products = [
  // CATEGORY: TV
  {
    src: "/EProducts/Samsung 65inch.jpg",
    title: "Samsung 138cm (55 inch) Crystal 4K Vision AI Smart TV",
    OriginalPrice: 45999,
    MRP: 65999,
    category: "TVs",
  },
  {
    src: "/EProducts/OnePlus TV.jpg",
    title: "OnePlus U1 138cm (55 inch) Ultra HD 4K Smart Google TV",
    OriginalPrice: 32999,
    MRP: 45999,
    category: "TVs",
  },
  {
    src: "/EProducts/LG 164cm.jpg",
    title: "LG 139cm (55 inch) Ultra HD 4K Smart LED TV",
    OriginalPrice: 42990,
    MRP: 62990,
    category: "TVs",
  },
  {
    src: "/EProducts/MI Q1 75inch.png",
    title: "Xiaomi Mi TV 5X 138cm (55 inch) QLED 4K Smart Android TV",
    OriginalPrice: 49999,
    MRP: 69999,
    category: "TVs",
  },
  {
    src: "/EProducts/VU 55inch.jpg",
    title: "VU 139cm (55 inch) Premium QLED 4K Ultra HD Smart TV",
    OriginalPrice: 35999,
    MRP: 49999,
    category: "TVs",
  },
  {
    src: "/EProducts/Sony Bravia XR 85-inch 4K HDR OLED.jpg",
    title: "Sony Bravia 2 138cm (55 inch) 4K Ultra HD Smart LED TV",
    OriginalPrice: 54990,
    MRP: 74990,
    category: "TVs",
  },
  {
    src: "/EProducts/TCL C655 138cm (55 inch) QLED 4K Google TV.webp",
    title: "TCL C655 138cm (55 inch) QLED 4K Google TV",
    OriginalPrice: 42990,
    MRP: 59990,
    category: "TVs",
  },
  {
    src: "/EProducts/Hisense 139cm (55 inch) Ultra HD 4K Smart Google TV.jpg",
    title: "Hisense 139cm (55 inch) Ultra HD 4K Smart Google TV",
    OriginalPrice: 37990,
    MRP: 52990,
    category: "TVs",
  },
  {
    src: "/EProducts/Philips 139cm (55 inch) Ultra HD 4K Android Smart TV.jpg",
    title: "Philips 139cm (55 inch) Ultra HD 4K Android Smart TV",
    OriginalPrice: 34990,
    MRP: 49990,
    category: "TVs",
  },
  {
    src: "/EProducts/Acer 109cm (43 inch) Full HD Smart LED TV.webp",
    title: "Acer 109cm (43 inch) Full HD Smart LED TV",
    OriginalPrice: 19999,
    MRP: 29999,
    category: "TVs",
  },
  {
    src: "/EProducts/Toshiba 108cm (43 inch) Ultra HD 4K Smart LED TV.webp",
    title: "Toshiba 108cm (43 inch) Ultra HD 4K Smart LED TV",
    OriginalPrice: 28990,
    MRP: 42990,
    category: "TVs",
  },
  {
    src: "/EProducts/Motorola EnvisionX 108cm (43 inch) HD Ready Smart LED TV.webp",
    title: "Motorola EnvisionX 108cm (43 inch) HD Ready Smart LED TV",
    OriginalPrice: 15999,
    MRP: 24999,
    category: "TVs",
  },
  {
    src: "/EProducts/Nokia 108cm (43 inch) Ultra HD 4K Smart Android TV.jpg",
    title: "Nokia 108cm (43 inch) Ultra HD 4K Smart Android TV",
    OriginalPrice: 24999,
    MRP: 35999,
    category: "TVs",
  },
  {
    src: "/EProducts/Blaupunkt 55inch.webp",
    title: "Blaupuntt 108cm (43 inch) HD Ready Smart LED TV",
    OriginalPrice: 12999,
    MRP: 19999,
    category: "TVs",
  },
  {
    src: "/EProducts/Samsung 163cm (65 inch) Crystal 4K Ultra HD Smart TV.webp",
    title: "Samsung 163cm (65 inch) Crystal 4K Ultra HD Smart TV",
    OriginalPrice: 79999,
    MRP: 119999,
    category: "TVs",
  },
  {
    src: "/EProducts/Sony Bravia 164cm (65 inch) 4K Ultra HD Smart LED TV.jpeg",
    title: "Sony Bravia 164cm (65 inch) 4K Ultra HD Smart LED TV",
    OriginalPrice: 109990,
    MRP: 149990,
    category: "TVs",
  },
  {
    src: "/EProducts/LG 164cm (65 inch) Ultra HD 4K Smart LED TV.jpg",
    title: "LG 164cm (65 inch) Ultra HD 4K Smart LED TV",
    OriginalPrice: 84990,
    MRP: 119990,
    category: "TVs",
  },
  {
    src: "/EProducts/Samsung 189cm (75 inch) QLED 4K Smart TV.jpg",
    title: "Samsung 189cm (75 inch) QLED 4K Smart TV",
    OriginalPrice: 149990,
    MRP: 219990,
    category: "TVs",
  },
  {
    src: "/EProducts/Xiaomi Mi TV 5 Pro 139cm (55 inch) QLED 4K.jpg",
    title: "Xiaomi Mi TV 5 Pro 139cm (55 inch) QLED 4K",
    OriginalPrice: 44999,
    MRP: 64999,
    category: "TVs",
  },
  {
    src: "/EProducts/TCL 164cm (65 inch) C745 QLED 4K Google TV.webp",
    title: "TCL 164cm (65 inch) C745 QLED 4K Google TV",
    OriginalPrice: 89990,
    MRP: 129990,
    category: "TVs",
  },
  {
    src: "/EProducts/OnePlus U1S 164cm (65 inch) 4K Ultra HD Smart TV.jpg",
    title: "OnePlus U1S 164cm (65 inch) 4K Ultra HD Smart TV",
    OriginalPrice: 54999,
    MRP: 79999,
    category: "TVs",
  },
  {
    src: "/EProducts/Mi TV 4A Pro 108cm (43 inch) HD Ready Smart TV.avif",
    title: "Mi TV 4A Pro 108cm (43 inch) HD Ready Smart TV",
    OriginalPrice: 17999,
    MRP: 27999,
    category: "TVs",
  },
  {
    src: "/EProducts/Philips 164cm (65 inch) 4K Ultra HD Android TV.webp",
    title: "Philips 164cm (65 inch) 4K Ultra HD Android TV",
    OriginalPrice: 69990,
    MRP: 99990,
    category: "TVs",
  },
  {
    src: "/EProducts/Motorola 164cm (65 inch) 4K Ultra HD Smart TV.webp",
    title: "Motorola 164cm (65 inch) 4K Ultra HD Smart TV",
    OriginalPrice: 49999,
    MRP: 74999,
    category: "TVs",
  },
  {
    src: "/EProducts/Nokia 139cm (55 inch) 4K Ultra HD Smart TV.jpg",
    title: "Nokia 139cm (55 inch) 4K Ultra HD Smart TV",
    OriginalPrice: 32999,
    MRP: 49999,
    category: "TVs",
  },

  // CATEGORY: SMARTPHONES
  {
    src: "/EProducts/Iphone 16 128GB Blue.jpg",
    title: "Iphone 16 (128GB) - Blue",
    OriginalPrice: 69900,
    MRP: 79900,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Vivo V60e 5G pink.jpg",
    title: "Vivo V60e 5G (8GB RAM, 256GB) - Royal Bronze",
    OriginalPrice: 27999,
    MRP: 34999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB) - Titanium Black.jpg",
    title: "Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB) - Titanium Black",
    OriginalPrice: 129999,
    MRP: 149999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Google Pixel 9 Pro (16GB RAM, 256GB) - Obsidian.webp",
    title: "Google Pixel 9 Pro (16GB RAM, 256GB) - Obsidian",
    OriginalPrice: 99999,
    MRP: 119999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/OnePlus 13 (16GB RAM, 512GB) - Flowy Emerald.jpg",
    title: "OnePlus 13 (16GB RAM, 512GB) - Flowy Emerald",
    OriginalPrice: 69999,
    MRP: 89999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Iphone 15 Pro Max (256GB) - Natural Titanium.jpg",
    title: "Iphone 15 Pro Max (256GB) - Natural Titanium",
    OriginalPrice: 159900,
    MRP: 179900,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Samsung Galaxy Z Fold 6 (12GB RAM, 512GB) - Navy.webp",
    title: "Samsung Galaxy Z Fold 6 (12GB RAM, 512GB) - Navy",
    OriginalPrice: 149999,
    MRP: 179999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Xiaomi 14 Ultra (16GB RAM, 512GB) - Black.webp",
    title: "Xiaomi 14 Ultra (16GB RAM, 512GB) - Black",
    OriginalPrice: 99999,
    MRP: 129999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/iQOO 13 (12GB RAM, 256GB) - Legend.jpg",
    title: "iQOO 13 (12GB RAM, 256GB) - Legend",
    OriginalPrice: 52999,
    MRP: 69999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Nothing Phone 2a Plus (12GB RAM, 256GB) - Grey.webp",
    title: "Nothing Phone 2a Plus (12GB RAM, 256GB) - Black",
    OriginalPrice: 27999,
    MRP: 35999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Motorola Edge 50 Pro (8GB RAM, 256GB) - Luxe Lavender.jpg",
    title: "Motorola Edge 50 Pro (8GB RAM, 256GB) - Luxe Lavender",
    OriginalPrice: 29999,
    MRP: 42999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Realme GT 7 Pro (16GB RAM, 512GB) - Galaxy Grey.webp",
    title: "Realme GT 7 Pro (16GB RAM, 512GB) - Galaxy Grey",
    OriginalPrice: 59999,
    MRP: 79999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Poco F6 Pro (12GB RAM, 512GB) - White.jpg",
    title: "Poco F6 Pro (12GB RAM, 512GB) - White",
    OriginalPrice: 41999,
    MRP: 55999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Oppo Find X8 Pro (16GB RAM, 512GB) - Pearl White.webp",
    title: "Oppo Find X8 Pro (16GB RAM, 512GB) - Pearl White",
    OriginalPrice: 79999,
    MRP: 99999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Asus ROG Phone 9 (16GB RAM, 512GB) - Phantom Black.avif",
    title: "Asus ROG Phone 9 (16GB RAM, 512GB) - Phantom Black",
    OriginalPrice: 99999,
    MRP: 129999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Samsung Galaxy A55 5G (8GB RAM, 256GB) - Awesome Iceblue.jpg",
    title: "Samsung Galaxy A55 5G (8GB RAM, 256GB) - Awesome Iceblue",
    OriginalPrice: 35999,
    MRP: 47999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/OnePlus Nord CE 4 (8GB RAM, 256GB) - Celadon Marble.webp",
    title: "OnePlus Nord CE 4 (8GB RAM, 256GB) - Celadon Marble",
    OriginalPrice: 22999,
    MRP: 29999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/iPhone 14 (128GB) - Midnight.webp",
    title: "Iphone 14 (128GB) - Midnight",
    OriginalPrice: 54999,
    MRP: 69900,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Google Pixel 8a (8GB RAM, 128GB) - Bay Blue.webp",
    title: "Google Pixel 8a (8GB RAM, 128GB) - Bay Blue",
    OriginalPrice: 35999,
    MRP: 49999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Redmi Note 14 Pro+ 5G (12GB RAM, 256GB) - Titan Gold.png",
    title: "Redmi Note 14 Pro+ 5G (12GB RAM, 256GB) - Titan Gold",
    OriginalPrice: 29999,
    MRP: 42999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Nothing Phone 2a (8GB RAM, 128GB) - White.jpg",
    title: "Nothing Phone 2a (8GB RAM, 128GB) - White",
    OriginalPrice: 19999,
    MRP: 27999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Samsung Galaxy Z Flip 6 (12GB RAM, 256GB) - Mint.webp",
    title: "Samsung Galaxy Z Flip 6 (12GB RAM, 256GB) - Mint",
    OriginalPrice: 89999,
    MRP: 109999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Motorola Razr 50 Ultra (12GB RAM, 512GB) - Hot Pink.webp",
    title: "Motorola Razr 50 Ultra (12GB RAM, 512GB) - Hot Pink",
    OriginalPrice: 79999,
    MRP: 99999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/Vivo X100 Pro (16GB RAM, 512GB) - Asteroid Black.png",
    title: "Vivo X100 Pro (16GB RAM, 512GB) - Asteroid Black",
    OriginalPrice: 89999,
    MRP: 119999,
    category: "Smartphones",
  },
  {
    src: "/EProducts/iQOO Neo 9 Pro (12GB RAM, 256GB) - Conqueror Black.jpg",
    title: "iQOO Neo 9 Pro (12GB RAM, 256GB) - Conqueror Black",
    OriginalPrice: 34999,
    MRP: 47999,
    category: "Smartphones",
  },

  // CATEGORY: LAPTOPS
  {
    src: "/EProducts/Apple MacBook Air M3 (8GB RAM, 256GB SSD) - Midnight.jpg",
    title: "Apple MacBook Air M3 (8GB RAM, 256GB SSD) - Midnight",
    OriginalPrice: 92900,
    MRP: 114900,
    category: "Laptops",
  },
  {
    src: "/EProducts/ASUS ROG Strix G16 (RTX 4070, 16GB RAM, 1TB SSD).jpg",
    title: "ASUS ROG Strix G16 (RTX 4070, 16GB RAM, 1TB SSD)",
    OriginalPrice: 149990,
    MRP: 189990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Dell XPS 15 (Intel Core i7, 16GB RAM, 512GB SSD).avif",
    title: "Dell XPS 15 (Intel Core i7, 16GB RAM, 512GB SSD)",
    OriginalPrice: 149990,
    MRP: 199990,
    category: "Laptops",
  },
  {
    src: "/EProducts/HP Spectre x360 (Intel Core i7, 16GB RAM, 1TB SSD).jpg",
    title: "HP Spectre x360 (Intel Core i7, 16GB RAM, 1TB SSD)",
    OriginalPrice: 129990,
    MRP: 169990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Apple MacBook Pro 16 M3 Max (36GB RAM, 1TB SSD).jpg",
    title: "Apple MacBook Pro 16 M3 Max (36GB RAM, 1TB SSD)",
    OriginalPrice: 299900,
    MRP: 349900,
    category: "Laptops",
  },
  {
    src: "/EProducts/Lenovo ThinkPad X1 Carbon (Intel Core i7, 16GB RAM, 512GB).jpg",
    title: "Lenovo ThinkPad X1 Carbon (Intel Core i7, 16GB RAM, 512GB)",
    OriginalPrice: 135000,
    MRP: 175000,
    category: "Laptops",
  },
  {
    src: "/EProducts/Acer Predator Helios Neo 16 (RTX 4060, 16GB RAM).jpg",
    title: "Acer Predator Helios Neo 16 (RTX 4060, 16GB RAM)",
    OriginalPrice: 109990,
    MRP: 149990,
    category: "Laptops",
  },
  {
    src: "/EProducts/MSI Stealth 14 AI (Intel Core Ultra 7, 16GB RAM).jpg",
    title: "MSI Stealth 14 AI (Intel Core Ultra 7, 16GB RAM)",
    OriginalPrice: 129990,
    MRP: 169990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Microsoft Surface Laptop 6 (Intel Core Ultra 7, 16GB).jpg",
    title: "Microsoft Surface Laptop 6 (Intel Core Ultra 7, 16GB)",
    OriginalPrice: 119990,
    MRP: 159990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Razer Blade 16 (RTX 4080, 32GB RAM, 1TB SSD).jpg",
    title: "Razer Blade 16 (RTX 4080, 32GB RAM, 1TB SSD)",
    OriginalPrice: 289990,
    MRP: 349990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Samsung Galaxy Book4 Pro 360 (Intel Core Ultra 7).jpg",
    title: "Samsung Galaxy Book4 Pro 360 (Intel Core Ultra 7)",
    OriginalPrice: 134990,
    MRP: 174990,
    category: "Laptops",
  },
  {
    src: "/EProducts/LG Gram 17 (Intel Core i7, 16GB RAM, 1TB SSD).jpg",
    title: "LG Gram 17 (Intel Core i7, 16GB RAM, 1TB SSD)",
    OriginalPrice: 159990,
    MRP: 199990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Gigabyte AORUS 16X (RTX 4070, 16GB RAM).jpg",
    title: "Gigabyte AORUS 16X (RTX 4070, 16GB RAM)",
    OriginalPrice: 149990,
    MRP: 199990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Alienware m18 R2 (RTX 4090, 64GB RAM, 2TB SSD).jpg",
    title: "Alienware m18 R2 (RTX 4090, 64GB RAM, 2TB SSD)",
    OriginalPrice: 349990,
    MRP: 429990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Lenovo IdeaPad Pro 5 (AMD Ryzen 7, 16GB RAM, 512GB).jpg",
    title: "Lenovo IdeaPad Pro 5 (AMD Ryzen 7, 16GB RAM, 512GB)",
    OriginalPrice: 79990,
    MRP: 109990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Apple MacBook Air 15 M3 (16GB RAM, 512GB SSD).webp",
    title: "Apple MacBook Air 15 M3 (16GB RAM, 512GB SSD)",
    OriginalPrice: 134900,
    MRP: 164900,
    category: "Laptops",
  },
  {
    src: "/EProducts/ASUS TUF Gaming F15 (RTX 4060, 16GB RAM, 512GB SSD).webp",
    title: "ASUS TUF Gaming F15 (RTX 4060, 16GB RAM, 512GB SSD)",
    OriginalPrice: 99990,
    MRP: 139990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Dell Inspiron 16 Plus (Intel Core i7, 16GB RAM, 1TB).webp",
    title: "Dell Inspiron 16 Plus (Intel Core i7, 16GB RAM, 1TB)",
    OriginalPrice: 109990,
    MRP: 149990,
    category: "Laptops",
  },
  {
    src: "/EProducts/HP Pavilion Plus 14 (Intel Core i7, 16GB RAM, 1TB SSD).webp",
    title: "HP Pavilion Plus 14 (Intel Core i7, 16GB RAM, 1TB SSD)",
    OriginalPrice: 89990,
    MRP: 129990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Acer Swift Go 14 OLED (AMD Ryzen 7, 16GB RAM, 512GB).webp",
    title: "Acer Swift Go 14 OLED (AMD Ryzen 7, 16GB RAM, 512GB)",
    OriginalPrice: 84990,
    MRP: 119990,
    category: "Laptops",
  },
  {
    src: "/EProducts/MSI Creator Z16 (Intel Core i9, RTX 3060, 32GB RAM).jpg",
    title: "MSI Creator Z16 (Intel Core i9, RTX 3060, 32GB RAM)",
    OriginalPrice: 179990,
    MRP: 229990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Lenovo Legion Pro 5 (RTX 4070, 16GB RAM, 1TB SSD).webp",
    title: "Lenovo Legion Pro 5 (RTX 4070, 16GB RAM, 1TB SSD)",
    OriginalPrice: 149990,
    MRP: 199990,
    category: "Laptops",
  },
  {
    src: "/EProducts/ASUS Zenbook Pro 14 OLED (Intel Core i7, 16GB RAM).jpg",
    title: "ASUS Zenbook Pro 14 OLED (Intel Core i7, 16GB RAM)",
    OriginalPrice: 119990,
    MRP: 159990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Dell Alienware x16 R1 (RTX 4090, 32GB RAM).jpg",
    title: "Dell Alienware x16 R1 (RTX 4090, 32GB RAM)",
    OriginalPrice: 329990,
    MRP: 399990,
    category: "Laptops",
  },
  {
    src: "/EProducts/Apple MacBook Pro 14 M3 Pro (18GB RAM, 512GB SSD).jpg",
    title: "Apple MacBook Pro 14 M3 Pro (18GB RAM, 512GB SSD)",
    OriginalPrice: 199900,
    MRP: 249900,
    category: "Laptops",
  },

  // CATEGORY: AUDIO
  {
    src: "/EProducts/Sony WH-1000XM5 Wireless Noise Cancelling Headphones.webp",
    title: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    OriginalPrice: 26990,
    MRP: 34990,
    category: "Audio",
  },
  {
    src: "/EProducts/Apple AirPods Pro 2nd Gen with USB-C.jpg",
    title: "Apple AirPods Pro 2nd Gen with USB-C",
    OriginalPrice: 24900,
    MRP: 28900,
    category: "Audio",
  },
  {
    src: "/EProducts/Bose QuietComfort 45 Noise Cancelling Headphones.webp",
    title: "Bose QuietComfort 45 Noise Cancelling Headphones",
    OriginalPrice: 26900,
    MRP: 32900,
    category: "Audio",
  },
  {
    src: "/EProducts/JBL Flip 6 Portable Bluetooth Speaker.jpg",
    title: "JBL Flip 6 Portable Bluetooth Speaker",
    OriginalPrice: 10999,
    MRP: 14999,
    category: "Audio",
  },
  {
    src: "/EProducts/Soundcore Headphone.png",
    title: "Anker Soundcore Space Q45 Wireless ANC Headphones",
    OriginalPrice: 8999,
    MRP: 14999,
    category: "Audio",
  },
  {
    src: "/EProducts/Skullcandy Crusher Evo Wireless Headphones.jpg",
    title: "Skullcandy Crusher Evo Wireless Headphones",
    OriginalPrice: 15999,
    MRP: 22999,
    category: "Audio",
  },
  {
    src: "/EProducts/boAt Nirvana Ion TWS Earbuds with 120H Playback.jpg",
    title: "boAt Nirvana Ion TWS Earbuds with 120H Playback",
    OriginalPrice: 1999,
    MRP: 4999,
    category: "Audio",
  },
  {
    src: "/EProducts/Noise Buds VS104 Pro ANC TWS Earbuds.jpg",
    title: "Noise Buds VS104 Pro ANC TWS Earbuds",
    OriginalPrice: 1499,
    MRP: 3999,
    category: "Audio",
  },
  {
    src: "/EProducts/Samsung Galaxy Buds 3 Pro Wireless Earbuds.jpg",
    title: "Samsung Galaxy Buds 3 Pro Wireless Earbuds",
    OriginalPrice: 14999,
    MRP: 19999,
    category: "Audio",
  },
  {
    src: "/EProducts/JBL Charge 5 Waterproof Portable Speaker.jpg",
    title: "JBL Charge 5 Waterproof Portable Speaker",
    OriginalPrice: 12999,
    MRP: 17999,
    category: "Audio",
  },
  {
    src: "/EProducts/Marshall Stanmore III Wireless Bluetooth Speaker.jpg",
    title: "Marshall Stanmore III Wireless Bluetooth Speaker",
    OriginalPrice: 34999,
    MRP: 45999,
    category: "Audio",
  },
  {
    src: "/EProducts/Beats Studio Pro Wireless Headphones.webp",
    title: "Beats Studio Pro Wireless Headphones",
    OriginalPrice: 34900,
    MRP: 44900,
    category: "Audio",
  },
  {
    src: "/EProducts/Jabra Elite 8 Active ANC True Wireless Earbuds.webp",
    title: "Jabra Elite 8 Active ANC True Wireless Earbuds",
    OriginalPrice: 14999,
    MRP: 19999,
    category: "Audio",
  },
  {
    src: "/EProducts/Sony WF-1000XM5 True Wireless Earbuds.jpg",
    title: "Sony WF-1000XM5 True Wireless Earbuds",
    OriginalPrice: 19990,
    MRP: 27990,
    category: "Audio",
  },
  {
    src: "/EProducts/Bose SoundLink Revolve+ II Portable Speaker.jpg",
    title: "Bose SoundLink Revolve+ II Portable Speaker",
    OriginalPrice: 22900,
    MRP: 29900,
    category: "Audio",
  },
  {
    src: "/EProducts/Marshall Emberton II Portable Speaker.jpg",
    title: "Marshall Emberton II Portable Speaker",
    OriginalPrice: 13999,
    MRP: 18999,
    category: "Audio",
  },
  {
    src: "/EProducts/OnePlus Buds Pro 3 ANC TWS Earbuds.jpg",
    title: "OnePlus Buds Pro 3 ANC TWS Earbuds",
    OriginalPrice: 9999,
    MRP: 14999,
    category: "Audio",
  },
  {
    src: "/EProducts/Realme Buds Air 6 Pro TWS Earbuds.jpg",
    title: "Realme Buds Air 6 Pro TWS Earbuds",
    OriginalPrice: 4999,
    MRP: 7999,
    category: "Audio",
  },
  {
    src: "/EProducts/Nothing Ear (2) True Wireless Earbuds.jpg",
    title: "Nothing Ear (2) True Wireless Earbuds",
    OriginalPrice: 9999,
    MRP: 14999,
    category: "Audio",
  },
  {
    src: "/EProducts/boAt Airdopes 441 Pro TWS Earbuds.jpg",
    title: "boAt Airdopes 441 Pro TWS Earbuds",
    OriginalPrice: 2499,
    MRP: 4499,
    category: "Audio",
  },
  {
    src: "/EProducts/Sennheiser HD 450BT Active Noise Cancelling.jpg",
    title: "Sennheiser HD 450BT Active Noise Cancelling",
    OriginalPrice: 11990,
    MRP: 17990,
    category: "Audio",
  },
  {
    src: "/EProducts/LG XBOOM Go PL7 Portable Bluetooth Speaker.jpg",
    title: "LG XBOOM Go PL7 Portable Bluetooth Speaker",
    OriginalPrice: 9990,
    MRP: 14990,
    category: "Audio",
  },
  {
    src: "/EProducts/Bowers & Wilkins Pi7 S2 True Wireless Earbuds.jpg",
    title: "Bowers & Wilkins Pi7 S2 True Wireless Earbuds",
    OriginalPrice: 32900,
    MRP: 42900,
    category: "Audio",
  },
  {
    src: "/EProducts/Apple AirPods 3rd Generation with MagSafe Case.jpg",
    title: "Apple AirPods 3rd Generation with MagSafe Case",
    OriginalPrice: 18900,
    MRP: 22900,
    category: "Audio",
  },
  {
    src: "/EProducts/boAt Rockerz 550 Over-Ear Wireless Headphones.jpg",
    title: "boAt Rockerz 550 Over-Ear Wireless Headphones",
    OriginalPrice: 1999,
    MRP: 4999,
    category: "Audio",
  },

  // CATEGORY: WEARABLES
  {
    src: "/EProducts/Apple Watch Series 9 GPS 45mm Smartwatch.jpg",
    title: "Apple Watch Series 9 GPS 45mm Smartwatch",
    OriginalPrice: 41900,
    MRP: 48900,
    category: "Wearables",
  },
  {
    src: "/EProducts/Samsung Galaxy Watch 6 Classic 47mm Smartwatch.jpg",
    title: "Samsung Galaxy Watch 6 Classic 47mm Smart Watch",
    OriginalPrice: 27999,
    MRP: 37999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Apple Watch Ultra 2 GPS + Cellular 49mm.jpg",
    title: "Apple Watch Ultra 2 GPS + Cellular 49mm",
    OriginalPrice: 89900,
    MRP: 99900,
    category: "Wearables",
  },
  {
    src: "/EProducts/Samsung Galaxy Watch 5 Pro LTE Smartwatch.jpg",
    title: "Samsung Galaxy Watch 5 Pro LTE Smartwatch",
    OriginalPrice: 24999,
    MRP: 34999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Google Pixel Watch 2 WiFi Smartwatch.jpg",
    title: "Google Pixel Watch 2 WiFi Smartwatch",
    OriginalPrice: 27999,
    MRP: 37999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Apple Watch SE 2nd Gen GPS 44mm.jpg",
    title: "Apple Watch SE 2nd Gen GPS 44mm",
    OriginalPrice: 24900,
    MRP: 29900,
    category: "Wearables",
  },
  {
    src: "/EProducts/Fitbit Charge 6 Advanced Fitness Tracker.jpg",
    title: "Fitbit Charge 6 Advanced Fitness Tracker",
    OriginalPrice: 7999,
    MRP: 11999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Fitbit Versa 3 Smartwatch.jpg",
    title: "Fitbit Versa 3 Smartwatch",
    OriginalPrice: 14999,
    MRP: 19999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Garmin Fenix 7X Pro Sapphire Solar Smartwatch.jpg",
    title: "Garmin Fenix 7X Pro Sapphire Solar Smartwatch",
    OriginalPrice: 89990,
    MRP: 119990,
    category: "Wearables",
  },
  {
    src: "/EProducts/Garmin Venu 3S AMOLED Fitness Watch.jpg",
    title: "Garmin Venu 3S AMOLED Fitness Watch",
    OriginalPrice: 34990,
    MRP: 44990,
    category: "Wearables",
  },
  {
    src: "/EProducts/Amazfit GTR 4 Premium Smartwatch.jpg",
    title: "Amazfit GTR 4 Premium Smartwatch",
    OriginalPrice: 11999,
    MRP: 16999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Amazfit T-Rex Ultra Rugged GPS Smartwatch.jpg",
    title: "Amazfit T-Rex Ultra Rugged GPS Smartwatch",
    OriginalPrice: 19999,
    MRP: 27999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Fastrack FS1 Pro Smartwatch.jpg",
    title: "Fastrack FS1 Pro Smartwatch",
    OriginalPrice: 5999,
    MRP: 9999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Noise ColorFit Pro 5 Max Smartwatch.jpg",
    title: "Noise ColorFit Pro 5 Max Smartwatch",
    OriginalPrice: 3999,
    MRP: 7999,
    category: "Wearables",
  },
  {
    src: "/EProducts/NoiseFit Halo Premium Round Smartwatch.jpg",
    title: "NoiseFit Halo Premium Round Smartwatch",
    OriginalPrice: 3499,
    MRP: 6999,
    category: "Wearables",
  },
  {
    src: "/EProducts/boAt Xtend Pro Calling Smartwatch.jpg",
    title: "boAt Xtend Pro Calling Smartwatch",
    OriginalPrice: 2999,
    MRP: 6999,
    category: "Wearables",
  },
  {
    src: "/EProducts/boAt Lunar Connect Ace Pro Smartwatch.jpg",
    title: "boAt Lunar Connect Ace Pro Smartwatch",
    OriginalPrice: 7999,
    MRP: 12999,
    category: "Wearables",
  },
  {
    src: "/EProducts/CrossBeats Ignite S4 Max Smartwatch.jpg",
    title: "CrossBeats Ignite S4 Max Smartwatch",
    OriginalPrice: 4999,
    MRP: 9999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Fire-Boltt Invincible Plus Smartwatch.jpg",
    title: "Fire-Boltt Invincible Plus Smartwatch",
    OriginalPrice: 7999,
    MRP: 12999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Pebble Cosmos Max 1.81 inch Smartwatch.jpg",
    title: "Pebble Cosmos Max 1.81 inch Smartwatch",
    OriginalPrice: 3999,
    MRP: 7999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Fossil Gen 6 Wellness Edition Smartwatch.jpg",
    title: "Fossil Gen 6 Wellness Edition Smartwatch",
    OriginalPrice: 22999,
    MRP: 32999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Titan Smart 3 Premium Smartwatch.jpg",
    title: "Titan Smart 3 Premium Smartwatch",
    OriginalPrice: 7990,
    MRP: 11990,
    category: "Wearables",
  },
  {
    src: "/EProducts/Xiaomi Smart Band 8 Pro Fitness Tracker.jpg",
    title: "Xiaomi Smart Band 8 Pro Fitness Tracker",
    OriginalPrice: 3999,
    MRP: 5999,
    category: "Wearables",
  },
  {
    src: "/EProducts/OnePlus Watch 2R Smartwatch.png",
    title: "OnePlus Watch 2R Smartwatch",
    OriginalPrice: 15999,
    MRP: 24999,
    category: "Wearables",
  },
  {
    src: "/EProducts/Realme Watch 3 Pro AMOLED Smartwatch.jpg",
    title: "Realme Watch 3 Pro AMOLED Smartwatch",
    OriginalPrice: 5999,
    MRP: 9999,
    category: "Wearables",
  },
];

export default products;
